---
name: "CI"

on:
  push:
    branches:
      # Do not trigger on tags
      # https://stackoverflow.com/questions/68573888/how-can-i-not-execute-a-github-action-when-i-push-a-new-tag
      "**"
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
