---
name: "Tests"

on:
  workflow_call: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - run: python3 -m pip install poetry

    - run: poetry install --with dev

    - run: poetry run black --check ./

    - run: poetry run isort --check-only ./

    - run: poetry run mypy ./

    - run: poetry run pylint RobotmkLibrary/
