---
name: "Tests"

on:
  workflow_call: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - run: python3 -m pip install poetry

    - run: poetry install --with dev

    - run: poetry run black --check ./

    - run: poetry run isort --check-only ./

    - run: poetry run mypy ./

    - run: poetry run pylint RobotmkLibrary/
